FROM ubuntu:24.04 AS qt6-wasm
RUN apt update
RUN apt install -y python3 python3-pip build-essential git lsb-release libdbus-1-3 libpulse-mainloop-glib0 cmake
RUN pip install --break-system-packages aqtinstall
WORKDIR /opt/qt
RUN aqt install-qt linux desktop 6.9.0 linux_gcc_64
RUN aqt install-qt all_os wasm 6.9.0 wasm_singlethread
WORKDIR /opt/emscripten
RUN git clone https://github.com/emscripten-core/emsdk
WORKDIR /opt/emscripten/emsdk
RUN ./emsdk install 3.1.70
RUN ./emsdk activate 3.1.70
WORKDIR /home/user
